myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication_app.urls')), # путь к приложению аутентификации
    path('products/', include('products_app.urls')), # путь к приложению продуктов
    path('cart/', include('cart_app.urls')), # путь к приложению корзины
    path('', include('pages_app.urls')), # путь к приложению страниц
    path('orders/', include('orders_app.urls')), # путь к приложению заказов

] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders_app/urls.py
from django.urls import path
from . import views  # импорт представлений из текущего пакета

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),  # путь к созданию заказа
    # path('created/', views.order_created, name='created'),
    path('created/<int:order_id>/', views.order_created, name='created')

]

templates/about.html
{% extends 'base.html' %}
{% block title %}
{{ title }} - Интернет-магазин
{% endblock %}
{% block content %}
<table class="table table-striped">
    {{ html | safe }}
</table>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <style>
        body {
          background: #5A657A;
          color: white;
          font-family: "Roboto", sans-serif;
        }
        body h1 {
          margin-bottom: 20px;
        }
        body p {
          font-size: 18px;
          line-height: 30px;
        }
        body a {
          color: #FBD160;
        }

        svg {
          display: block;
          margin: 0 auto;
          overflow: visible !important;
        }
        svg #robot_1_ {
          animation-name: verticalAnimation;
          animation-duration: 1s;
          animation-iteration-count: infinite;
          animation-direction: alternate;
          animation-timing-function: ease-in-out;
        }
        svg #light_1_ {
          animation-name: blinkLight;
          animation-duration: 0.5s;
          animation-iteration-count: infinite;
          animation-direction: alternate;
          animation-timing-function: steps(2);
        }
        svg #leftEye_1_, svg #rightEye_1_ {
          animation-name: blinkEye;
          animation-duration: 1.8s;
          animation-iteration-count: infinite;
          animation-direction: alternate;
          animation-timing-function: linear;
          transform-origin: 50% 50%;
        }
        svg #leftArm_1_ {
          animation-name: moveLeftArm;
          animation-duration: 1s;
          animation-iteration-count: infinite;
          animation-direction: alternate;
          animation-timing-function: ease-in-out;
          transform-origin: 50% 10%;
          transition: all;
        }
        svg #rightArm_1_ {
          animation-name: moveRightArm;
          animation-duration: 1s;
          animation-iteration-count: infinite;
          animation-direction: alternate;
          animation-timing-function: ease-in-out;
          transform-origin: 50% 10%;
        }
        svg #shadow_1_ {
          animation-name: shadowAnimation;
          animation-duration: 1s;
          animation-iteration-count: infinite;
          animation-direction: alternate;
          animation-timing-function: ease-in-out;
          transform-origin: 50%;
        }

        @keyframes wave {
          0% {
            transform: rotate(120deg);
          }
          100% {
            transform: rotate(170deg);
          }
        }
        @keyframes moveLeftArm {
          0% {
            transform: rotate(0);
          }
          100% {
            transform: rotate(4deg);
          }
        }
        @keyframes moveRightArm {
          0% {
            transform: rotate(0);
          }
          100% {
            transform: rotate(-4deg);
          }
        }
        @keyframes shadowAnimation {
          0% {
            transform: scale(1);
            opacity: 0.4;
          }
          100% {
            transform: scale(1.15);
            opacity: 0.6;
          }
        }
        @keyframes verticalAnimation {
          0% {
            transform: translateY(-10px);
          }
          100% {
            transform: translateY(10px);
          }
        }
        @keyframes blinkLight {
          0% {
            opacity: 0;
          }
          100% {
            opacity: 1;
          }
        }
        @keyframes blinkEye {
          0% {
            transform: scaleY(0);
          }
          4% {
            transform: scaleY(1);
          }
        }

    </style>


    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
<div class="container-fluid">
    <!-- Шапка -->
    <div class="row">
        <div class="col-12 text-center">
            <!-- Логотип -->
            <img src="https://frontend-scripts.hb.bizmrg.com/assets/logo/geekbrains-logo-light.svg" alt="Логотип">

            <!-- Меню -->
            <ul class="nav nav-tabs justify-content-center">
                <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about/">О сайте</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/cart/">Корзина</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contacts/">Контакты</a>
                </li>
                <li class="nav-item">
                    {% if request.user.is_authenticated %}
                    Добро пожаловать,
                    {% if request.user.first_name %}
                    {% if not request.user.is_superuser %}
                    <a href="{% url 'profile' %}">{{ request.user.first_name }}</a>
                    {% else %}
                    {{ request.user.first_name }}
                    {% endif %}
                    {% else %}
                    <a href="{% url 'profile' %}">{{ request.user.username }}</a>
                    {% endif %}
                    | <a href="{% url 'logout' %}">Выйти</a>
                    {% else %}
                    <a href="{% url 'login' %}">Войти / Регистрация</a>
                    {% endif %}

                </li>

            </ul>
        </div>
    </div>

    <div class="row">
        <!-- Левая колонка для дополнительного меню товаров -->
        <div class="col-3">
            <!-- Дополнительное меню -->
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="/products/category_all/">Категории товаров</a>
                </li>
            </ul>
        </div>

        <!-- Основной контент -->
        <div class="col-6">
            {% block content %}
            Страницы не заполнена
            {% endblock %}
            <p><br><br></p>
        </div>

        <!-- Правая колонка -->
        <div class="col-3">
            <!-- Место под банеры -->

        </div>

    </div>

    <!-- Подвал -->
    <div class="row fixed-bottom modal-footer" style="background-color: rgba(128, 128, 128, 0.9);">
        <div class="col-12 text-center">
            <p>Сайт создан на Django</p>
        </div>
    </div>
</div>
</div>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% block title %}
Корзина - Интернет-магазин
{% endblock %}
{% block content %}

<table class="table table-striped">
    <thead>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li
                {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}

        </li>

        {% endfor %}
    </ul>
    {% endif %}

    <tr>
        <th></th>
        <th>Название товара</th>
        <th>Количество</th>
        <th>Цена</th>
        <th>Общая стоимость</th>
        <th></th>
    </tr>
    </thead>

    <tbody>

    {% load cart_tags %}

    {% for cart_product in cart_products %}
    <tr id="productRow{{ cart_product.product.id }}{{ cart_product.size.id }}">
        <td><img src="{{ cart_product.product.image.url }}" alt="Изображение товара" width="50" height="50"></td>
        <td><a href="{% url 'product_info' cart_product.product.id %}">{{ cart_product.product.name }}</a>
            <br>({{ cart_product.size.size }})
        </td>
        <td>

            <form method="post" action="{% url 'change_quantity' cart_product.product.id %}"
                  id="changeQuantityForm{{ cart_product.product.id }}{{ cart_product.size.id }}">
                {% csrf_token %}
                <input type="number" name="quantity" value="{{ cart_product.quantity }}" min="1" style="width: 50px;"
                       onchange="changeQuantity('{{ cart_product.product.id }}', '{{ cart_product.size.id }}')">
                <input type="hidden" name="size" value="{{ cart_product.size.id }}">
            </form>


        </td>
        <td>{{ cart_product.product.price }}</td>
        <td>{{ cart_product.product.price|total_price:cart_product.quantity }}</td>
        <td>
            <form method="post" action="{% url 'remove_from_cart' cart_product.product.id cart_product.size.id %}">
                {% csrf_token %}
                <input type="submit" value="Удалить">
            </form>

        </td>
    </tr>
    {% endfor %}


    </tbody>

</table>
<tr>
    <div id="availabilityMessage" style="display: none;"></div>
</tr>
<tr>
    <td>Количество товаров: {{ total_quantity }}</td>
    <td>Итого: {{ total_price }}</td>
    <td><p><a href="{% url 'orders:order_create' %}" class="btn btn-primary">Оформить заказ</a></p></td>
</tr>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        setInterval(function(){
            {% for cart_product in cart_products %}
            $.ajax({
                url: '/cart/check_availability/{{ cart_product.product.id }}/{{ cart_product.size.id }}/',
                success: function(data){
                    var product_size_id = '{{ cart_product.product.id }}_{{ cart_product.size.id }}';
                    if (data[product_size_id] < 3) {
                        var row = document.getElementById('productRow{{ cart_product.product.id }}{{ cart_product.size.id }}');
                        row.style.backgroundColor = 'yellow';
                        var message = '{{ cart_product.product.name }} <br>размера {{ cart_product.size.size }} заканчивается. Осталось менее 3 шт.';
                        document.getElementById('availabilityMessage').innerHTML = message;
                        document.getElementById('availabilityMessage').style.display = 'block';
                    }
                }
            });
            {% endfor %}
        }, 600000);
    });

        function changeQuantity(productId, sizeId) {
        var form = document.getElementById('changeQuantityForm' + productId + sizeId);
        form.submit();
    }


</script>

{% endblock %}

templates/category_all.html
{% extends 'base.html' %}
{% block title %}
{{ title }} - Интернет-магазин
{% endblock %}
{% block content %}
<h2>Все категории товаров</h2>
<style>
    .client-card {
        margin: 20px;
    }
</style>

<div class="container">
    <div class="row">
        {% for category in categories %}
            <div class="col-md-3 client-card">
                <h3><a href="{% url 'product_category' category %}" title="Карточка {{ category }}">{{ category }}</a></h3>

            </div>
            {% if forloop.counter|divisibleby:3 %}
                </div><div class="row">
            {% endif %}
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/create.html
{% extends 'base.html' %}
{% block content %}
<h1>Оформление заказа</h1>
<form method="post">
    {% csrf_token %}
    <tr>
    <tr>
        <td> Количество товаров: {{ total_quantity }} | Общая стоимость: {{ total_price }} руб. + Доставка: {{ delivery_price }} руб.
        </td>
    </tr>
    </tr>
    <tr>
        <p>Адрес доставки:
            {{ request.user.profile.adress_of_delivery_line_1 }}
            {{ profile.adress_of_delivery_line_2 }}
            {{ request.user.profile.adress_of_city }}
            {{ request.user.profile.adress_of_state }}
            {{ request.user.profile.adress_of_zip }}
        </p>

    </tr>
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Оформить заказ</button>
</form>
{% endblock %}

templates/created.html
{% extends 'base.html' %}
{% block title %}
Заказ создан - Интернет-магазин
{% endblock %}
{% block content %}
<div class="alert alert-success" role="alert">
  Ваш заказ {{ order.id }} на сумму {{ order.get_total_cost }} руб. успешно создан.

</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}
{{ title }} - Интернет-магазин
{% endblock %}
{% block content %}
<table class="table table-striped">
    {{ html | safe }}

</table>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block title %}
{{ title }} - Интернет-магазин
{% endblock %}
{% block content %}
  <h2>Вход | Регистрация</h2>
  <form method="post">
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Войти</button>
    <button type="button" onclick="location.href='{% url 'signup' %}'">Регистрация</button>
  </form>
{% endblock %}

templates/product_category.html
{% extends 'base.html' %}
{% block title %}
{{ category_names_titles }} - Интернет-магазин
{% endblock %}
{% block content %}
<h2>Товары в категории: {{ category_names_titles }}</h2>
<style>
    .product-card {
        margin: 20px;
    }
    .product-card img {
        width: 100%;
        height: auto;
    }
</style>

<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-md-3 product-card">
            <h3><a href="{% url 'product_info' product.id %}">{{ product.name }}</a></h3>
            <p>Цена: {{ product.price }}</p>
            <p>
                {% if product.quantity > 3 %}
                Остаток в наличии
                {% elif product.quantity > 0 %}
                Осталось мало
                {% else %}
                Нет в наличии
                {% endif %}
            </p>
            {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.name }}">
            {% endif %}
        </div>
        {% if forloop.counter|divisibleby:4 %}
    </div>
    <div class="row">
        {% endif %}
        {% endfor %}
    </div>
    <tr>
        <td><a href="javascript:history.back()">Назад</a></td>
    </tr>
</div>
{% endblock %}

templates/product_info.html
{% extends 'base.html' %}
{% block title %}
{{ product.title }} - Интернет-магазин
{% endblock %}
{% block content %}
<table class="table table-striped">
    <tr>
        <td>Название товара: {{ product.name }}</td>
        <td rowspan="6"><img src="{{ product.image.url }}" alt="Изображение товара" width="250" height="250"></td>
    </tr>
    <tr>
        <td>Описание товара: {{ product.description | safe }}</td>
    </tr>
    <tr>
        <td>Бренд: {{ product.brand }}</td>
    </tr>
    <tr>
        <td>
            <form id="productForm" method="post" action="{% url 'add_to_cart' product.id %}">
                {% csrf_token %}
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <select id="sizeSelect" name="size">
                    {% for size_quantity in productSizeQuantity %}
                    <option value="{{ size_quantity.size.id }}">{{ size_quantity.size.size }}</option>
                    {% endfor %}
                </select>
                <div id="stockStatus"></div>
                {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li
                    {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <input type="submit" id="addToCartButton" value="Добавить в корзину"
                       {% if not productSizeQuantity %}disabled{% endif %}>
            </form>

            <script>
                document.getElementById('sizeSelect').addEventListener('change', function() {
                    var selectedSizeId = this.value;
                    {% for size_quantity in productSizeQuantity %}
                        if ({{ size_quantity.size.id }} == selectedSizeId) {
                            var quantity = {{ size_quantity.quantity }};
                            var stockStatusDiv = document.getElementById('stockStatus');
                            var addToCartButton = document.getElementById('addToCartButton');
                            if (quantity > 5) {
                                stockStatusDiv.textContent = 'Остаток в наличии';
                                addToCartButton.disabled = false;
                            } else if (quantity > 0) {
                                stockStatusDiv.textContent = 'Осталось мало';
                                addToCartButton.disabled = false;
                            } else {
                                stockStatusDiv.textContent = 'Нет в наличии';
                                addToCartButton.disabled = true;

                            }

                        }
                    {% endfor %}
                });
                document.getElementById('sizeSelect').dispatchEvent(new Event('change'));
            </script>

        </td>
    </tr>
    <tr>
        <td>Цена товара: {{ product.price }}</td>
    </tr>
    <tr>
        <td><a href="{% url 'product_category' category %}">Вернуться к списку товаров</a></td>
    </tr>
</table>


{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block title %}
{{ title }} - Информация о клиенте
{% endblock %}
{% block content %}
<h2>Информация о клиенте: {{ profile.first_name }}</h2>
<table class="table table-striped">
    <tr>
        <td>Имя:</td>
        <td>{{ request.user.profile.first_name }} </td>
        <td rowspan="6"><img src="{{ request.user.profile.avatar.url }}" alt="Фото клиента" width="250" height="250"></td>
    </tr>
    <tr>
        <td>Фамилия:</td>
        <td>{{ request.user.profile.last_name }}</td>
    </tr>
    <tr>
        <td>Дата рождения:</td>
        <td>{{ request.user.profile.date_of_birth }}</td>
    </tr>
    <tr>
        <td>Email:</td>
        <td>{{ request.user.email }}</td>
    </tr>
    <tr>
        <td>Телефон:</td>
        <td>{{ request.user.profile.phone_number }}</td>
    </tr>
    <tr>
        <td>Адрес доставки:</td>
        <td>{{ request.user.profile.adress_of_delivery_line_1 }}
            {{ profile.adress_of_delivery_line_2 }}
            {{ request.user.profile.adress_of_city }}
            {{ request.user.profile.adress_of_state }}
            {{ request.user.profile.adress_of_zip }}</td>

    </tr>
    <tr>
        <td>Дата регистрации:</td>
        <td>{{ request.user.profile.add_data }}</td>
    </tr>
    <tr>
        <td>
            <a href="{% url 'edit_profile' %}">Редактировать профиль</a>
        </td>
    </tr>

</table>
{% endblock %}

templates/profile_edit.html
{% extends 'base.html' %}
{% block title %}
{{ title }} - Редактирование профиля
{% endblock %}
{% block content %}
<h2>Редактирование профиля: {{ profile.first_name }}</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить изменения</button> <a href="{% url 'profile' %}">Отмена</a>
</form>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block title %}
{{ title }} - Интернет-магазин
{% endblock %}
{% block content %}
  <h2>Регистрация</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Зарегистрироваться</button>
  </form>
{% endblock %}